export const FORMULARIO_CARPETA = 'FORMULARIO_CARPETA';
export const OBTENER_CARPETAS = 'OBTENER_CARPETAS';
export const AGREGAR_CARPETA = 'AGREGAR_CARPETA';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const CARPETA_ACTUAL = 'CARPETA_ACTUAL';
export const ELIMINAR_CARPETA = 'ELIMINAR_CARPETA';
export const CARPETA_ERROR = 'CARPETA_ERROR';


export const TAREAS_CARPETA = 'TAREAS_CARPETA';
export const AGREGAR_TAREA = 'AGREGAR_TAREA';
export const VALIDAR_TAREA = 'VALIDAR_TAREA';
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA';
export const TAREA_ACTUAL = 'TAREA_ACTUAL';
export const ACTUALIZAR_TAREA = 'ACTUALIZAR_TAREA';